final products = [
  {
    'id': '0',
    'title': 'Bathu Khalanga',
    'price': 1500.00,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Bathu',
    'sizes': [4, 5, 6, 7, 8, 9],
  },
  {
    'id': '1',
    'title': 'Konkhe 14',
    'price': 1200.00,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Konkhe kuhamba kahle',
    'sizes': [6, 7, 8],
  },
  {
    'id': '2',
    'title': 'ROF 990',
    'price': 990.00,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Root of Fame',
    'sizes': [3, 4, 5, 6, 7, 8],
  },
  {
    'id': '3',
    'title': 'Drip Solemate',
    'price': 1200.00,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Drip',
    'sizes': [5, 6, 7, 8],
  },
  {
    'id': '4',
    'title': 'Bathu Mesh Edition',
    'price': 1200.00,
    'imageUrl': 'assets/images/shoes_5.png',
    'company': 'Bathu',
    'sizes': [6, 7, 8, 9, 10],
  },
  {
    'id': '5',
    'title': 'Drip Likwidz',
    'price': 1000.00,
    'imageUrl': 'assets/images/shoes_6.png',
    'company': 'Drip',
    'sizes': [6, 7, 8, 9],
  },
  {
    'id': '6',
    'title': 'Konkhe',
    'price': 1500.00,
    'imageUrl': 'assets/images/shoes_7.png',
    'company': 'Konkhe kuhamba kahle',
    'sizes': [6, 7, 8, 9],
  },
  {
    'id': '7',
    'title': 'Jordan Shoes',
    'price': 2650.95,
    'imageUrl': 'assets/images/shoes_8.png',
    'company': 'Nike',
    'sizes': [7, 8, 9, 10],
  },
];
